es:
  languageCode: es
  languageName: Spanish
  #contentDir: content
  # Uncomment for multilingual sites, and move the default content into corresponding sub-folder.
  

# Uncomment for multilingual sites, and customize the following config.
# zh:
#   languageCode: zh
#   languageName: 简体中文
#   contentDir: content/zh
#   title: 中文标题
